"""Live-Ollama OCR end-to-end tests — Phase D / Wave 6 (E-07).

These tests run the full PDF Tier 2 escalation path and the
``ImageExtractor`` happy path against a *real* local Ollama daemon
serving ``qwen2.5vl:7b``. They are gated by the ``requires_ollama``
pytest marker — ``tests/integration/conftest.py`` auto-skips them at
collection time when the daemon is unreachable or the model is not
pulled. CI (which has no Ollama) therefore stays green; a developer
machine with ``ollama serve`` running and ``qwen2.5vl:7b`` pulled
actually exercises every assertion below.

Wall-clock budget per test: ~30-60 s on Apple Silicon (M1 Pro and up).
Individual tests carry ``@pytest.mark.timeout(120)`` to allow some
headroom for the first call (model warm-up) without letting a runaway
hang sit forever.

Fixtures used (all generated by ``scripts/build_fixture_corpus.py``):

- ``tests/fixtures/multi_format_corpus/pdf/scanned-paper.pdf`` —
  image-only PDF with no text layer; the ``PdfDigitalExtractor`` flags
  it as sparse and escalates.
- ``tests/fixtures/multi_format_corpus/images/screenshot.png`` —
  monospace text screenshot (code-editor mockup).
- ``tests/fixtures/multi_format_corpus/images/photo-of-receipt.jpg`` —
  synthetic receipt with line items + TOTAL.
- ``tests/fixtures/multi_format_corpus/images/diagram.webp`` —
  two-circle "A → B" diagram.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from corpus_forge.extractors.image import ImageExtractor
from corpus_forge.extractors.pdf import PdfDigitalExtractor
from corpus_forge.vlm.base import VLMTimeoutError
from corpus_forge.vlm.ollama import OllamaVLM

pytestmark = [pytest.mark.integration, pytest.mark.requires_ollama]

_FIXTURE_ROOT = Path(__file__).resolve().parent.parent / "fixtures" / "multi_format_corpus"
_SCANNED_PDF = _FIXTURE_ROOT / "pdf" / "scanned-paper.pdf"
_SCREENSHOT = _FIXTURE_ROOT / "images" / "screenshot.png"
_RECEIPT = _FIXTURE_ROOT / "images" / "photo-of-receipt.jpg"
_DIAGRAM = _FIXTURE_ROOT / "images" / "diagram.webp"

# Minimum text length we'll accept from a live VLM. Trivial fixtures
# can produce very short responses; 50 chars is enough to assert the
# round-trip actually returned content without forcing brittle prose
# assertions.
_MIN_TEXT_LEN = 50

# Default model tag for the test suite. Matches the conftest probe —
# any ``qwen2.5vl`` tag is acceptable, but :7b is the documented
# default and the one the CI / dev guide tells users to pull.
_MODEL = "qwen2.5vl:7b"


def _make_vlm(*, timeout_s: float = 120.0, model: str = _MODEL) -> OllamaVLM:
    """Construct an :class:`OllamaVLM` against the local daemon.

    Tests do *not* call ``warmup()`` here — the conftest skip already
    proved the daemon is reachable + the model is pulled.
    """
    return OllamaVLM(model=model, ollama_url="http://localhost:11434", timeout_s=timeout_s)


@pytest.mark.timeout(180)
def test_pdf_escalation_happy_path() -> None:
    """Scanned PDF → VLM OCR escalation produces non-empty Markdown.

    Drives the canonical Wave 5 escalation path end-to-end:

    1. ``PdfDigitalExtractor`` reads the text layer (empty for the
       scanned fixture) and flips ``sparse_text_layer = True``.
    2. ``_escalate`` rasterises via pdf2image and calls ``extract_page``
       on the live Ollama VLM for each page (only 1 here).
    3. The returned document has ``tier = "ocr_escalated"``, the
       backend / page-count metadata, and the ``("ocr", "ollama")``
       label.
    """
    assert _SCANNED_PDF.is_file(), (
        f"Fixture missing: {_SCANNED_PDF}. Re-run `uv run python scripts/build_fixture_corpus.py`."
    )
    vlm = _make_vlm()
    extractor = PdfDigitalExtractor(vlm=vlm, ocr_enabled=True, min_chars_per_page=100)

    doc = extractor.extract(_SCANNED_PDF)

    assert len(doc.text) > _MIN_TEXT_LEN, (
        f"Live OCR returned only {len(doc.text)} chars from a 1-page scanned "
        f"fixture. The VLM may be misconfigured or the prompt is empty. "
        f"Response preview: {doc.text[:200]!r}"
    )
    assert doc.metadata.get("tier") == "ocr_escalated", (
        f"Expected tier=ocr_escalated; got {doc.metadata.get('tier')!r}. "
        f"Full metadata: {doc.metadata!r}"
    )
    assert doc.metadata.get("pages_ocr_count", 0) >= 1
    assert doc.metadata.get("ocr_backend") == "ollama"
    assert ("ocr", "ollama") in doc.labels
    assert ("format", "pdf") in doc.labels


@pytest.mark.timeout(120)
def test_image_extractor_happy_path() -> None:
    """ImageExtractor + Ollama VLM produces non-empty Markdown for a screenshot."""
    assert _SCREENSHOT.is_file(), f"Fixture missing: {_SCREENSHOT}"
    vlm = _make_vlm()
    extractor = ImageExtractor(vlm=vlm)

    doc = extractor.extract(_SCREENSHOT)

    assert len(doc.text) > _MIN_TEXT_LEN, (
        f"ImageExtractor returned only {len(doc.text)} chars from a "
        f"600x400 code-editor screenshot. Response preview: {doc.text[:200]!r}"
    )
    assert doc.chunker_hint == "markdown"
    assert ("format", "image") in doc.labels
    assert ("ocr", "ollama") in doc.labels


@pytest.mark.timeout(240)
def test_all_three_image_fixtures_round_trip() -> None:
    """Every P1 image fixture round-trips through the live VLM.

    Quality assertions stay loose — we only require non-empty Markdown
    for each fixture. The point is to surface fixture-shape regressions
    (e.g. someone shipped a 0-byte WebP) and VLM contract regressions
    (e.g. ``describe_image`` returning bytes instead of str).
    """
    vlm = _make_vlm()
    extractor = ImageExtractor(vlm=vlm)
    for fixture in (_SCREENSHOT, _RECEIPT, _DIAGRAM):
        assert fixture.is_file(), f"Fixture missing: {fixture}"
        doc = extractor.extract(fixture)
        assert doc.text, f"VLM returned empty text for {fixture.name}"
        assert isinstance(doc.text, str), f"Expected str, got {type(doc.text).__name__}"


@pytest.mark.timeout(60)
def test_vlm_timeout_degrades_to_tier1() -> None:
    """An extremely short timeout forces ``VLMTimeoutError`` on the live VLM.

    Asserts the documented degradation contract:

    - For PDFs: ``PdfDigitalExtractor._escalate`` catches
      ``VLMTimeoutError`` per-page and inserts a placeholder; the
      caller still receives a populated ``ExtractedDocument``. With a
      single-page fixture the placeholder *is* the entire body, so we
      assert ``ocr_escalated`` tier was reached (i.e. escalation
      attempted) and the placeholder marker appears in the text.

    A separate assertion confirms the raw VLM call would have raised
    ``VLMTimeoutError`` -- proves the timeout knob actually fires
    against the live daemon and isn't being swallowed before it
    reaches our exception map.

    The timeout is set to 0.1 s -- well below qwen2.5vl:7b's first-token
    floor on M-series (typically 1-3 s even on a warm model). 1.0 s
    was previously found to race when the model is already loaded in
    memory from earlier tests in the same session.
    """
    vlm = _make_vlm(timeout_s=0.1)
    # Direct VLM call -- must raise VLMTimeoutError.
    # Use the real screenshot fixture so Ollama doesn't reject the
    # request body for being a non-image upstream of the model call.
    image_bytes = _SCREENSHOT.read_bytes()
    with pytest.raises(VLMTimeoutError):
        vlm.extract_page(image_bytes, page_number=1)

    # End-to-end PDF path with the same tight timeout. The extractor
    # must NOT raise — it catches VLMTimeoutError per page and inserts
    # a ``<!-- VLM timeout on page N -->`` placeholder.
    extractor = PdfDigitalExtractor(vlm=vlm, ocr_enabled=True, min_chars_per_page=100)
    doc = extractor.extract(_SCANNED_PDF)
    assert "VLM timeout" in doc.text, (
        f"Expected '<!-- VLM timeout on page N -->' placeholder in text; got: {doc.text[:200]!r}"
    )
    # Even with every page timing out, escalation was attempted — the
    # tier metadata reflects that (pages_ocr_count == 1).
    assert doc.metadata.get("tier") == "ocr_escalated"
    assert doc.metadata.get("pages_ocr_count") == 1
