#!/usr/bin/env bash
# corpus-forge — Postgres tuning drop-in (Debian / Ubuntu).
#
# Writes a conf.d drop-in (e.g. /etc/postgresql/17/main/conf.d/corpus-forge.conf)
# rather than editing postgresql.conf directly. Easier to revert
# (delete the file) and harder to break (PG concatenates conf.d files
# after the main config).
#
# Tuning formulae (locked for Phase R):
#   shared_buffers         = 25% of total RAM
#   effective_cache_size   = 75% of total RAM
#   work_mem               = max(64MB,  RAM_GB * 8MB)
#   maintenance_work_mem   = max(512MB, RAM_GB * 64MB)
#   wal_compression        = on
#
# See docs/deployment/postgres.md (Tuning section) for the rationale and
# the worked-example sizing table.

set -euo pipefail

PROG_NAME="$(basename "$0")"
RAM_GB=""
DRY_RUN=0
PG_VERSION="${CF_PG_VERSION:-17}"
CONFIG_DIR=""

print_help() {
  cat <<EOF
${PROG_NAME} — write a corpus-forge tuning drop-in for PostgreSQL.

USAGE:
  ${PROG_NAME} --ram GB [FLAGS]

REQUIRED:
  --ram GB             Total RAM available to the Postgres host (integer GB).

FLAGS:
  --help               Show this help and exit 0.
  --dry-run            Print the generated corpus-forge.conf to stdout;
                       write nothing to disk.
  --pg-version N       Postgres major version (default 17). Env: CF_PG_VERSION.
  --config-dir PATH    Override the config directory (default
                       /etc/postgresql/\${PG_VERSION}/main).

OUTPUT:
  A drop-in file at <config-dir>/conf.d/corpus-forge.conf containing:
    shared_buffers, effective_cache_size, work_mem,
    maintenance_work_mem, wal_compression.
  Restart or reload postgresql to pick up the new values:
    sudo systemctl reload postgresql

EXAMPLES:
  ${PROG_NAME} --ram 16 --dry-run
  sudo ${PROG_NAME} --ram 32

See docs/deployment/postgres.md for the sizing rationale.
EOF
}

while (( $# > 0 )); do
  case "$1" in
    --help) print_help; exit 0 ;;
    --ram)
      (( $# >= 2 )) || { echo "${PROG_NAME}: --ram requires a value" >&2; exit 64; }
      RAM_GB="$2"; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    --pg-version)
      (( $# >= 2 )) || { echo "${PROG_NAME}: --pg-version requires a value" >&2; exit 64; }
      PG_VERSION="$2"; shift 2 ;;
    --config-dir)
      (( $# >= 2 )) || { echo "${PROG_NAME}: --config-dir requires a value" >&2; exit 64; }
      CONFIG_DIR="$2"; shift 2 ;;
    *)
      echo "${PROG_NAME}: unknown flag: $1" >&2
      echo "Run '${PROG_NAME} --help' for usage." >&2
      exit 64
      ;;
  esac
done

if [[ -z "${RAM_GB}" ]]; then
  echo "${PROG_NAME}: --ram is required (integer GB)" >&2
  exit 2
fi

if ! [[ "${RAM_GB}" =~ ^[0-9]+$ ]] || (( RAM_GB <= 0 )); then
  echo "${PROG_NAME}: --ram must be a positive integer (got '${RAM_GB}')" >&2
  exit 64
fi

if [[ -z "${CONFIG_DIR}" ]]; then
  CONFIG_DIR="/etc/postgresql/${PG_VERSION}/main"
fi

# ---------------------------------------------------------------------------
# Compute values
# ---------------------------------------------------------------------------

# shared_buffers = 25% of RAM, in GB.
SHARED_BUFFERS_GB=$(( RAM_GB / 4 ))
# Below 4 GB the integer division gives 0 — clamp to 1 GB.
if (( SHARED_BUFFERS_GB < 1 )); then SHARED_BUFFERS_GB=1; fi
SHARED_BUFFERS="${SHARED_BUFFERS_GB}GB"

# effective_cache_size = 75% of RAM, in GB.
EFFECTIVE_CACHE_GB=$(( RAM_GB * 3 / 4 ))
if (( EFFECTIVE_CACHE_GB < 1 )); then EFFECTIVE_CACHE_GB=1; fi
EFFECTIVE_CACHE="${EFFECTIVE_CACHE_GB}GB"

# work_mem = max(64MB, RAM_GB * 8MB).
WORK_MEM_MB=$(( RAM_GB * 8 ))
if (( WORK_MEM_MB < 64 )); then WORK_MEM_MB=64; fi
WORK_MEM="${WORK_MEM_MB}MB"

# maintenance_work_mem = max(512MB, RAM_GB * 64MB).
MAINT_MB=$(( RAM_GB * 64 ))
if (( MAINT_MB < 512 )); then MAINT_MB=512; fi
# Prefer GB notation if exactly divisible by 1024 (16 GB → 512, no rewrite;
# 32 GB → 1024, rewrite to 1GB).
if (( MAINT_MB == 1024 )); then
  MAINT_WORK_MEM="1GB"
else
  MAINT_WORK_MEM="${MAINT_MB}MB"
fi

# ---------------------------------------------------------------------------
# Render
# ---------------------------------------------------------------------------

CONF_BODY=$(cat <<EOF
# corpus-forge tuning drop-in.
# Generated by ${PROG_NAME} for ${RAM_GB} GB of system RAM.
# Edit values by re-running this script with a different --ram, or
# delete this file to revert to PostgreSQL defaults.
#
# Drop-in path: ${CONFIG_DIR}/conf.d/corpus-forge.conf
# Reload to apply:   sudo systemctl reload postgresql

shared_buffers = ${SHARED_BUFFERS}
effective_cache_size = ${EFFECTIVE_CACHE}
work_mem = ${WORK_MEM}
maintenance_work_mem = ${MAINT_WORK_MEM}
wal_compression = on
EOF
)

if (( DRY_RUN == 1 )); then
  echo "# DRY-RUN — would write to ${CONFIG_DIR}/conf.d/corpus-forge.conf"
  echo "${CONF_BODY}"
  exit 0
fi

if [[ ! -d "${CONFIG_DIR}" ]]; then
  echo "${PROG_NAME}: config dir ${CONFIG_DIR} not found." >&2
  echo "Pass --config-dir or check the --pg-version." >&2
  exit 1
fi

mkdir -p "${CONFIG_DIR}/conf.d"
TARGET="${CONFIG_DIR}/conf.d/corpus-forge.conf"
printf "%s\n" "${CONF_BODY}" > "${TARGET}"

echo "[corpus-forge tune] wrote ${TARGET}"
echo "[corpus-forge tune] reload Postgres: sudo systemctl reload postgresql"
