"""Pure-filesystem checks for the CLIP-lane image fixtures.

The two text-free images generated by ``build_clip_images()`` in
``scripts/build_fixture_corpus.py`` feed the live-CLIP end-to-end tests
under ``tests/integration/test_multimodal_embed_e2e.py``. This unit test
needs no model and no DB — it just asserts the committed bytes are
present, open as RGB at the expected size, and differ from each other.

pytestmark: pytest.mark.unit
"""

from __future__ import annotations

from pathlib import Path

import pytest

pytestmark = pytest.mark.unit


_FIXTURE_ROOT = Path(__file__).resolve().parent.parent / "fixtures" / "multi_format_corpus"
_SCENE = _FIXTURE_ROOT / "images" / "scene-landscape.png"
_BLOCKS = _FIXTURE_ROOT / "images" / "abstract-blocks.png"
_EXPECTED_SIZE = (320, 320)


def test_clip_image_fixtures_exist() -> None:
    assert _SCENE.is_file(), (
        f"Fixture missing: {_SCENE}. Re-run `uv run python scripts/build_fixture_corpus.py`."
    )
    assert _BLOCKS.is_file(), (
        f"Fixture missing: {_BLOCKS}. Re-run `uv run python scripts/build_fixture_corpus.py`."
    )


def test_clip_image_fixtures_are_rgb_expected_size() -> None:
    from PIL import Image

    for path in (_SCENE, _BLOCKS):
        with Image.open(path) as img:
            assert img.mode == "RGB", f"{path.name} mode is {img.mode!r}, expected 'RGB'"
            assert img.size == _EXPECTED_SIZE, (
                f"{path.name} size is {img.size}, expected {_EXPECTED_SIZE}"
            )


def test_clip_image_fixtures_differ_from_each_other() -> None:
    assert _SCENE.read_bytes() != _BLOCKS.read_bytes(), (
        "scene-landscape.png and abstract-blocks.png have identical bytes; "
        "they must be visually distinct so CLIP embeds them differently."
    )
