"""Unit tests for ``HeuristicQualityEnricher`` (RFC P1 foundation).

The RFC's acceptance criterion is "known good vs known bad chunk
orderings." We pin that ordering plus the per-signal contributions
so future tuning of the constants doesn't accidentally invert the
known-good/known-bad relationship.
"""

from __future__ import annotations

import pytest

from corpus_forge.quality import HeuristicQualityEnricher, HeuristicQualityScore
from corpus_forge.quality.heuristic import (
    DEFAULT_LOW_QUALITY_THRESHOLD,
    _punctuation_balance,
    _repetition_ratio,
    _shouting_ratio,
    _token_rate,
)

# ── Fixture chunks: a small set covering the documented failure modes ──


GOOD_PROSE = (
    "The conversation chunker walks a JSONL session file line by line. "
    "Each line is one of a small set of typed events; only user, "
    "assistant, and attachment carry message content."
)

GOOD_PROSE_TECHNICAL = (
    "Pydantic v2's default_factory captures the callable reference at "
    "class-definition time, so monkeypatching the helper later does "
    "NOT redirect already-defined models."
)

PURE_WHITESPACE = "   \n\n\t\t   "

ALL_PUNCTUATION = "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

REPEATED_NGRAM = "abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc"

ALL_CAPS = (
    "EVERY WORD IN THIS SENTENCE IS SHOUTED AND THAT'S NOT HOW HUMAN "
    "PROSE NORMALLY READS WHEN A PARAGRAPH HAS BEEN GENERATED BY A "
    "MISBEHAVING MODEL."
)

EMPTY = ""
EMPTY_AFTER_STRIP = "\n   \t  "


# ── Tests ───────────────────────────────────────────────────────────


class TestEmptyAndDegenerateInputs:
    """Empty / whitespace-only text returns a zero score."""

    def test_empty_returns_all_zero(self) -> None:
        s = HeuristicQualityEnricher().score(EMPTY)
        assert s.quality_score == 0.0
        assert s == HeuristicQualityScore(0.0, 0.0, 0.0, 0.0, 0.0)

    def test_whitespace_only_returns_all_zero(self) -> None:
        s = HeuristicQualityEnricher().score(EMPTY_AFTER_STRIP)
        assert s.quality_score == 0.0


class TestGoodVsBadOrdering:
    """The RFC's acceptance criterion: known good > known bad."""

    @pytest.mark.parametrize(
        ("good", "bad"),
        [
            (GOOD_PROSE, PURE_WHITESPACE),
            (GOOD_PROSE, ALL_PUNCTUATION),
            (GOOD_PROSE, REPEATED_NGRAM),
            (GOOD_PROSE, ALL_CAPS),
            (GOOD_PROSE_TECHNICAL, PURE_WHITESPACE),
            (GOOD_PROSE_TECHNICAL, ALL_PUNCTUATION),
            (GOOD_PROSE_TECHNICAL, REPEATED_NGRAM),
            (GOOD_PROSE_TECHNICAL, ALL_CAPS),
        ],
    )
    def test_good_outranks_bad(self, good: str, bad: str) -> None:
        enr = HeuristicQualityEnricher()
        good_score = enr.score(good).quality_score
        bad_score = enr.score(bad).quality_score
        assert good_score > bad_score, (
            f"good {good!r:.40s} scored {good_score:.3f}, bad {bad!r:.40s} scored {bad_score:.3f}"
        )

    def test_good_prose_scores_above_low_quality_threshold(self) -> None:
        score = HeuristicQualityEnricher().score(GOOD_PROSE).quality_score
        assert score >= DEFAULT_LOW_QUALITY_THRESHOLD, (
            f"good prose scored below the low-quality threshold: {score:.3f}"
        )

    def test_known_bad_falls_below_low_quality_threshold(self) -> None:
        enr = HeuristicQualityEnricher()
        for bad in (PURE_WHITESPACE, ALL_PUNCTUATION, REPEATED_NGRAM):
            score = enr.score(bad).quality_score
            assert score < DEFAULT_LOW_QUALITY_THRESHOLD, (
                f"known-bad {bad!r:.40s} scored above threshold: {score:.3f}"
            )


class TestIsLowQualityWrapper:
    """`is_low_quality` is the threshold wrapper around `score`."""

    def test_default_threshold(self) -> None:
        enr = HeuristicQualityEnricher()
        assert enr.is_low_quality(PURE_WHITESPACE) is True
        assert enr.is_low_quality(GOOD_PROSE) is False

    def test_custom_threshold(self) -> None:
        enr = HeuristicQualityEnricher()
        # Threshold 1.0 → everything that isn't perfect is "low quality."
        assert enr.is_low_quality(GOOD_PROSE, threshold=1.0) is True
        # Threshold 0.0 → nothing is low quality (open lower bound).
        assert enr.is_low_quality(PURE_WHITESPACE, threshold=0.0) is False


# ── Per-signal contract pins ────────────────────────────────────────


class TestTokenRateSignal:
    """Out-of-band ratios decay; in-band stays at 1.0."""

    def test_all_whitespace_zero(self) -> None:
        assert _token_rate("    \n\n") == 0.0

    def test_no_whitespace_decays_toward_zero(self) -> None:
        # A long run of letters with no spaces — far outside the band.
        out = _token_rate("a" * 200)
        assert 0.0 <= out < 0.3

    def test_balanced_prose_in_band(self) -> None:
        # GOOD_PROSE has well-distributed whitespace.
        assert _token_rate(GOOD_PROSE) == 1.0


class TestPunctuationBalanceSignal:
    """Excess punctuation density decays the signal."""

    def test_no_punctuation_full_score(self) -> None:
        assert _punctuation_balance("hello world this is plain prose") == 1.0

    def test_all_punctuation_decays_hard(self) -> None:
        assert _punctuation_balance(ALL_PUNCTUATION) < 0.1

    def test_normal_prose_full_score(self) -> None:
        # GOOD_PROSE has commas and periods but well below the ceiling.
        assert _punctuation_balance(GOOD_PROSE) == 1.0


class TestRepetitionRatioSignal:
    """Heavy n-gram repetition drags the signal toward 0."""

    def test_pure_prose_near_one(self) -> None:
        # GOOD_PROSE has no significant repetition.
        assert _repetition_ratio(GOOD_PROSE) > 0.85

    def test_perfect_repeat_near_zero(self) -> None:
        # "abcabcabc..." — the trigram "abc" covers ~100 % of text.
        assert _repetition_ratio(REPEATED_NGRAM) < 0.1

    def test_too_short_returns_one(self) -> None:
        # Below the minimum n, no repetition can be detected.
        assert _repetition_ratio("ab") == 1.0


class TestShoutingRatioSignal:
    """Uppercase letter fraction is the inverse of the signal."""

    def test_no_letters_full_score(self) -> None:
        # Numbers and punctuation only — nothing to shout.
        assert _shouting_ratio("12345 !!! 6789") == 1.0

    def test_all_caps_near_zero(self) -> None:
        assert _shouting_ratio(ALL_CAPS) < 0.2

    def test_mixed_case_high(self) -> None:
        # GOOD_PROSE has normal sentence capitalisation.
        assert _shouting_ratio(GOOD_PROSE) > 0.9


class TestScoreShape:
    """The composite is in [0.0, 1.0] for every fixture."""

    @pytest.mark.parametrize(
        "fixture",
        [
            GOOD_PROSE,
            GOOD_PROSE_TECHNICAL,
            PURE_WHITESPACE,
            ALL_PUNCTUATION,
            REPEATED_NGRAM,
            ALL_CAPS,
            EMPTY,
            EMPTY_AFTER_STRIP,
        ],
    )
    def test_composite_in_unit_interval(self, fixture: str) -> None:
        s = HeuristicQualityEnricher().score(fixture).quality_score
        assert 0.0 <= s <= 1.0, f"composite out of [0, 1]: {s}"


class TestDeterminismAndStatelessness:
    """Same input → same output across multiple calls + multiple instances."""

    def test_same_instance_same_input(self) -> None:
        enr = HeuristicQualityEnricher()
        a = enr.score(GOOD_PROSE)
        b = enr.score(GOOD_PROSE)
        assert a == b

    def test_distinct_instances_same_input(self) -> None:
        a = HeuristicQualityEnricher().score(GOOD_PROSE)
        b = HeuristicQualityEnricher().score(GOOD_PROSE)
        assert a == b
